
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_automation
    username: ysfaltn
    password: 'ysfaltn'
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: GMT+3
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true
server:
  port: 8070
